### ISSUE TITLE
About Size of IsLand

### ISSUE THREAD

**Issue by haha252** [Euphillya/Skyllia#13]
(Before start, I must say that  **my English is not well** ! Hope your forgiveness. **And I will try the latest version soon.**)

In today's testing, we found that if the distance between two island  **smaller than 2000** ,folia will put them to **one thread** .

![Screenshot_20240120-155623](https://github.com/Euphillya/Skyllia/assets/55837097/21df9a3d-dda7-48cb-a7e2-e4d2b15557ae)

I set `simulation-distance` in `server.properties` to `8` first.

I opened this server to 11 real player.And make 9 of them to the default generated islands. **Distance of Each Island is nearly 1K**,because I set the config of the size of the island to `500`.

Then I create 3 plantform at A(1000,50,1000), B(2000,50,2000), C(4000,50,4000), and put 3 players to each plantfrom.

The result of the testing is that:
folia put A and B in one thread, but put C in another thread.
It's so strange.

So, we hope to make the size of the island to **2048** to slove this problem.

**Comment by Euphillya** [comment]
The /TPS displays only the 3 most resource-hungry regions. We see on your screen that there are 6 regions in total, including 1 in the World. So I guess there's a minimum of 2 up to 5 in the Skyblock world. 
Then each island is separated from the center by a maximum of 512 blocks, as only one region file has an island. Example: r.0.0.mca will contain only one island at its center. 
Is it possible to provide me with a spark link so that I can more easily see what's going on?

Traduit avec DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by haha252** [comment]
oh, I'm sorry that i ignored that...
If i can reapper, i'll send it to you
thank you!

**Comment by haha252** [comment]
I’m very sorry, I reopened this issue again. I have tested it many times and found that there is no way to divide it into two regions. How can I troubleshoot the problem using Spark?

**Comment by Euphillya** [comment]
Try checking directly with Folia's discord or github to see if it's a config or something else.
You Can Always send link spark here

**Comment by haha252** [comment]
https://spark.lucko.me/nD2TiEyyQY

---------

in this test, I let my friend stop in `(0,100,0)`, and I tp to somewhere else.

in (1000,100,1000)
![Screenshot_20240124-175546](https://github.com/Euphillya/Skyllia/assets/55837097/68ab12a3-c79f-4f59-a06d-333907af7b61)

in (1500,100,1500)
![Screenshot_20240124-175615](https://github.com/Euphillya/Skyllia/assets/55837097/b6f2092f-51a8-4579-bee8-d220f92f2e4b)

in (2000,100,2000) it comes to 3 region.
![Screenshot_20240124-175649](https://github.com/Euphillya/Skyllia/assets/55837097/da72d1b6-735b-4dc4-bf8e-46ec90451c23)

Thank you very much.

**Comment by Euphillya** [comment]
![Screenshot_2024-01-24-11-30-29-742_com android chrome](https://github.com/Euphillya/Skyllia/assets/26461373/e1e4d52c-011e-4e9f-9724-91292fac824c)
![Screenshot_2024-01-24-11-30-33-777_com android chrome](https://github.com/Euphillya/Skyllia/assets/26461373/979e176e-6e91-4a5a-8ee6-ded301972893)
2 regions Folia / 20 are for Skyblock, so i think its good because only 1 player per région folia

**Comment by haha252** [comment]
oh, maybe it's because when I was testing before, the two of us ended up in two areas. Is it all that is needed for the data of the two of us on our respective empty islands? I thought it would take us the whole process from being together to being apart.

**Comment by haha252** [comment]
I found in this file, it shows it divide into 2 region, but in folia's command(/tps) it doesn't devide in two region.
so strange.

**Comment by Euphillya** [comment]
Send report to Folia

**Comment by haha252** [comment]
ok
